import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Ordered explicitly (rather than autogenerated) so the three guides read
// in the order a new shop owner should tackle them.
const sidebars: SidebarsConfig = {
  guidesSidebar: [
    "intro",
    "managing-products",
    "homepage-and-content",
    "orders-and-stripe",
  ],
};

export default sidebars;
