/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    pages: Page;
    products: Product;
    customers: Customer;
    orders: Order;
    feedback: Feedback;
    subscribers: Subscriber;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'footer-settings': FooterSetting;
    about: About;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'footer-settings': FooterSettingsSelect<false> | FooterSettingsSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers and og:image context. Keep it meaningful — it feeds the PDP SEO markup.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    stage?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The shop's product categories — drives the Shop filter chips, the footer's Shop column, and the /feedback + search category chips. Add, rename, or reorder here; no deploy needed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Auto-generated from the name. Used in filter-chip URLs/state.
   */
  slug?: string | null;
  /**
   * Lower numbers show first in the filter-chip row and the footer's Shop column.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Composable pages built from an ordered list of sections. The homepage lives here (slug "home") — add, remove, or drag to reorder sections in "Layout" below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * The homepage uses "home". Future landing pages would use their own slug.
   */
  slug: string;
  layout?:
    | (
        | {
            /**
             * The big headline. Use *word* for the coral script-accent style and _word_ for the outlined-stroke style (matches the current "painted" / "magic" treatment). A line on its own becomes a line break.
             */
            heading?: string | null;
            /**
             * The paragraph under the headline. Leave empty to use the default copy.
             */
            leadCopy?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading: string;
            copy: string;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            theme?: ('coral' | 'gold' | 'teal') | null;
            /**
             * Optional. Leave empty to start showing immediately.
             */
            activeFrom?: string | null;
            /**
             * Optional — the banner self-expires after this date. No need to remember to remove it.
             */
            activeTo?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'promoBanner';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'trustBand';
          }
        | {
            /**
             * Small label above the heading, e.g. "Shop the collection".
             */
            kicker?: string | null;
            /**
             * Leave either field empty to use the default copy.
             */
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productGrid';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'story';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            /**
             * Step numbers (01, 02, ...) are generated automatically from the order here — drag to reorder.
             */
            steps?:
              | {
                  title: string;
                  detail: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'process';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'moodboard';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'bespoke';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Auto-generated from the name. Powers the PDP URL — changing it breaks existing links.
   */
  slug?: string | null;
  /**
   * Add or rename categories in the Categories collection — no code change needed.
   */
  cat: number | Category;
  /**
   * Enter the price in pounds. e.g. 24.99 for £24.99. Stored as pence internally for Stripe.
   */
  price: number;
  /**
   * One line shown under the product name on cards — material, size, or a key detail. e.g. "Hand-crocheted cotton, approx 28cm".
   */
  meta: string;
  /**
   * Optional label shown on the product card. Leave empty for no badge.
   */
  tag?: ('bestseller' | 'new' | 'limited' | 'popular') | null;
  /**
   * Colour theme for the placeholder image when no real photo is uploaded (0–7). Each number maps to a different brand gradient.
   */
  palette: number;
  /**
   * The little icon shown in the placeholder image before real photos are added.
   */
  motif:
    'heart' | 'cushion' | 'bag' | 'flower' | 'bunny' | 'loop' | 'tassel' | 'ball' | 'abstract' | 'canvas' | 'portrait';
  /**
   * Upload real product photos here. The first one is used on the grid card. If empty, a generated placeholder is shown instead.
   */
  photos?: (number | Media)[] | null;
  /**
   * The main description shown on the product page. If left empty, a generic description is generated from the short description.
   */
  story?: string | null;
  /**
   * Bullet points shown under "The details" on the product page. e.g. "100% cotton yarn", "Approx 28cm tall".
   */
  specs?:
    | {
        spec: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown under "Looking after it". e.g. "Spot clean only with a damp cloth."
   */
  care?: string | null;
  /**
   * Shown in the coral line above the product name. e.g. "6–8 hours by hand", "an original, 1 of 1".
   */
  madeIn?: string | null;
  /**
   * Tab/search title for the product page. Falls back to the product name.
   */
  metaTitle?: string | null;
  /**
   * Shown in Google search results. Falls back to the product story if empty.
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One record per customer, shared across all of their orders. Kept up to date with their most recent contact/shipping details each time they check out — see an individual Order for what was actually shipped to at the time.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  /**
   * Looked up by email at checkout — one Customer per email address.
   */
  email: string;
  firstName: string;
  lastName: string;
  phone?: string | null;
  address1: string;
  address2?: string | null;
  city: string;
  postcode: string;
  country: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer orders — the CMS is the system of record for contact/shipping details. Stripe only processes payment.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * The customer this order belongs to (found-or-created by email at checkout). See the fields below for what was actually shipped to on THIS order specifically.
   */
  customer: number | Customer;
  status: 'pending' | 'paid' | 'payment_failed' | 'refunded';
  /**
   * Join key back to Stripe — the only thing Stripe and the CMS share about this order.
   */
  stripePaymentIntentId: string;
  email: string;
  firstName: string;
  lastName: string;
  phone?: string | null;
  address1: string;
  address2?: string | null;
  city: string;
  postcode: string;
  country: string;
  shippingMethod: 'standard' | 'express' | 'nextday';
  items: {
    productId: number;
    name: string;
    unitPrice: number;
    qty: number;
    lineTotal: number;
    id?: string | null;
  }[];
  subtotal: number;
  shipping: number;
  total: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer testimonials. 2-3 marked "Featured" show on the homepage; everything shows on /feedback.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: number;
  /**
   * Controls which card style renders: eBay shows a masked handle + verified-purchase badge, App shows a real name.
   */
  source: 'ebay' | 'app';
  quote: string;
  /**
   * eBay doesn't expose a per-review star rating on the public feedback profile (only an overall positive %) — default to 5 for sourced entries, all of which were left as positive/Verified purchase feedback.
   */
  rating: number;
  /**
   * Free-text product name as it appeared on eBay, or the product this review is about.
   */
  productName: string;
  /**
   * Which shop category this review is about — powers the /feedback category filter. Add or rename categories in the Categories collection.
   */
  cat: number | Category;
  /**
   * Masked eBay buyer ID, e.g. "j***n" — exactly as shown on the public feedback profile. Only used when source is eBay.
   */
  buyerHandle?: string | null;
  /**
   * Real name, shown for in-app named reviews only.
   */
  customerName?: string | null;
  /**
   * Shows the "Verified purchase" badge. True for all sourced eBay feedback.
   */
  verified?: boolean | null;
  /**
   * Show this one on the homepage highlight row (keep this to 2-3 entries).
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Stitch club mailing list — one record per subscribed email, submitted from the homepage footer's signup form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  /**
   * Looked up by email on signup — resubmitting the same address is a no-op, not an error.
   */
  email: string;
  /**
   * Where the signup came from — defaults to the only signup point that exists today.
   */
  source?: string | null;
  /**
   * Manually flipped by an admin on an unsubscribe request — no self-service unsubscribe flow exists yet.
   */
  unsubscribed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'feedback';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        stage?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              leadCopy?: T;
              id?: T;
              blockName?: T;
            };
        promoBanner?:
          | T
          | {
              heading?: T;
              copy?: T;
              ctaLabel?: T;
              ctaHref?: T;
              theme?: T;
              activeFrom?: T;
              activeTo?: T;
              id?: T;
              blockName?: T;
            };
        trustBand?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        productGrid?:
          | T
          | {
              kicker?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        story?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              steps?:
                | T
                | {
                    title?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        moodboard?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        bespoke?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  cat?: T;
  price?: T;
  meta?: T;
  tag?: T;
  palette?: T;
  motif?: T;
  photos?: T;
  story?: T;
  specs?:
    | T
    | {
        spec?: T;
        id?: T;
      };
  care?: T;
  madeIn?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  lastName?: T;
  phone?: T;
  address1?: T;
  address2?: T;
  city?: T;
  postcode?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  customer?: T;
  status?: T;
  stripePaymentIntentId?: T;
  email?: T;
  firstName?: T;
  lastName?: T;
  phone?: T;
  address1?: T;
  address2?: T;
  city?: T;
  postcode?: T;
  country?: T;
  shippingMethod?: T;
  items?:
    | T
    | {
        productId?: T;
        name?: T;
        unitPrice?: T;
        qty?: T;
        lineTotal?: T;
        id?: T;
      };
  subtotal?: T;
  shipping?: T;
  total?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  source?: T;
  quote?: T;
  rating?: T;
  productName?: T;
  cat?: T;
  buyerHandle?: T;
  customerName?: T;
  verified?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  unsubscribed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Turn a section off if it isn't ready for real customers yet (no real content, still being designed, etc). Off means it's skipped entirely — not shown empty or as a placeholder.
   */
  homepageSections?: {
    originalArtworks?: boolean | null;
    process?: boolean | null;
    studioJournal?: boolean | null;
    /**
     * Also controls the "Bespoke" nav link — off hides both the section and the link, so the nav never points at a section that isn't on the page.
     */
    bespoke?: boolean | null;
  };
  /**
   * Controls which testimonials the storefront shows on the homepage and /feedback.
   */
  feedback?: {
    /**
     * On launch, all feedback is migrated from the eBay store (masked buyer handle, no real name). Turn this off once there's enough organic in-app feedback (source: App) to stand on its own — eBay-sourced entries stay in the CMS but stop being returned to the storefront, no need to delete or re-tag them.
     */
    showEbaySourced?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-settings".
 */
export interface FooterSetting {
  id: number;
  /**
   * Shown in the footer's "Hello" column. Add or remove accounts here — no code change needed.
   */
  socialLinks?:
    | {
        /**
         * "Other" shows the label as plain text with no platform icon.
         */
        platform: 'instagram' | 'pinterest' | 'tiktok' | 'other';
        url: string;
        /**
         * Displayed handle, e.g. @yese.creations
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown in the footer's "Studio" column (Our story, Bespoke, Care guide, etc). Replaces the old code-level page-readiness flags — just add the link here once the page is live.
   */
  studioLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown in the thin bottom row of the footer (Shipping, Returns, Privacy, etc).
   */
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Theresa's bio, shown on the homepage's "My Story" section, the standalone /about page, and the fast in-app overlay — all three read from here, so nothing can drift out of sync.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * Small label above the heading, e.g. "My Story".
   */
  kicker?: string | null;
  /**
   * Use *word* for the coral script-accent style (matches the current "one" treatment).
   */
  heading?: string | null;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  signatureName?: string | null;
  signatureSubtitle?: string | null;
  /**
   * The small handwritten-style note next to the photos. Use a line break for a two-line note.
   */
  marginNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  homepageSections?:
    | T
    | {
        originalArtworks?: T;
        process?: T;
        studioJournal?: T;
        bespoke?: T;
      };
  feedback?:
    | T
    | {
        showEbaySourced?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-settings_select".
 */
export interface FooterSettingsSelect<T extends boolean = true> {
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  studioLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  signatureName?: T;
  signatureSubtitle?: T;
  marginNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}